### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by is06** [CanalTP/jungle-bot#4]

**Comment by ooga** [comment]
Heroku Tuto
- https://www.sitepoint.com/building-facebook-chat-bot-node-heroku/
- https://chatbotsmagazine.com/building-a-facebook-messenger-bot-using-nodejs-heroku-api-ai-8b53c1102531

**Comment by ooga** [comment]
AWS Tuto
- https://chatbotslife.com/write-a-serverless-slack-chat-bot-using-aws-e2d2432c380e
